branches:
  only:
  - master

services:
  - docker

script:
  - docker build -t y2khub/delete_messages_bot .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push y2khub/delete_messages_bot